### ISSUE TITLE
Ambiguous declaration of <listBibl> inside <div>

### ISSUE THREAD

**Issue by rvdb** [OpenEdition/tei.openedition#3]
When validating a document against [tei.openedition.1.5.xsd](http://lodel.org/ns/tei.openedition.1.5/tei.openedition.1.5.xsd), Oxygen flags following error for line 1579 of the XSD file:

    cos-nonambig: "http://www.tei-c.org/ns/1.0":listBibl and "http://www.tei-c.org/ns/1.0":listBibl (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.

    Start location: 1579:6
    End location: 1579:20
    URL: http://www.w3.org/TR/xmlschema-1/#cos-nonambig

I suspect the changes in commit https://github.com/OpenEdition/tei.openedition/commit/035df3f61bc4c2f616ef679934b979708b77f052 have created an ambiguous content model.

**Comment by jfriviere** [comment]
https://github.com/OpenEdition/tei.openedition/releases/tag/1.5.1 should fix the issue.
